enums:
- Fl::Fl_Option
- Fl_Labeltype
- Fl_Boxtype
- Fl_Mode

typedefs:
  Fl_Color: int64_t     # Actually int but Dart uses int64_t
  Fl_Align: int64_t     # Actually uint32_t but Dart uses int64_t
  Fl_Fontsize: int64_t  # Actually uint32_t but Dart uses int64_t
  Fl_Font: int64_t      # Actually uint32_t but Dart uses int64_t

drawfn:
- Fl_Widget
- Fl_Gl_Window
