name:         fltk
version:      0.0.3
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Dart bindings for FLTK!
homepage:     https://github.com/hermanbergwerf/fltk-dart
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  image:      ^1.1.26
  dartgl:     ^0.1.2
dev_dependencies:
  glob:       ^1.1.2
  yaml:       ^2.1.8
  mustache:   ^0.2.5
