name:         fltk
version:      0.0.1
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Dart bindings for FLTK!
homepage:     https://github.com/hermanbergwerf/fltk-dart
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
