name:         fltk
version:      0.0.5
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Dart bindings for FLTK!
homepage:     https://github.com/bergwerf/fltk-dart
environment:
  sdk:        '>=2.0.0-dev <3.0.0'
dependencies:
  color:      ^2.0.2
  image:      ^2.0.4
  dartgl:     ^0.1.3
  cairodart:  ^0.2.2
  watcher:    ^0.9.7+10
  vm_service_lib: ^0.3.8
dev_dependencies:
  glob:       ^1.1.7
  yaml:       ^2.1.15
  mustache:   ^1.0.2
